name: Pytest
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:
 
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
          
        - name: Install Pytest  
          run: pip3 install pytest
        
        - name: Install supporting softwares
          run: |
            pip install pytest-md
            pip install pytest-emoji


        - name: Check Out all files
          uses: actions/checkout@v4
          with:
            repository: angeljackal/Calculator_Pytest
            
            
        - name: Run Pytest
          run: pytest test_calculator.py
        

        - name: Compile pytest results  
          uses: pavelzw/pytest-action@v2
          with:
            verbose: true
            emoji: true
            job-summary: true
            custom-arguments: '-q'
            click-to-expand: true
            report-title: 'Test Report'

        - if: ${{ failure()}}
          uses: JasonEtco/create-an-issue@v2
          with:
            filename: .github/ISSUE_TEMPLATE.md

        - name: Publish Test Results xml
          uses: EnricoMi/publish-unit-test-result-action/composite@v2
          if: always()
          with:
            junit_files: 'report.xml'
        