name: Pytest
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:
        
        - name: Check Out and run pytest
          uses: actions/checkout@v4
          with:
            repository: angeljackal/Calculator_Pytest
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
          run: |
            pip install pytest
            pytest test_calculator.py
