name: Pytest
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:
        
        - name: Check Out
          uses: actions/checkout@v4
          with:
            repository: angeljackal/Calculator_Pytest
        
        - name: Setup Python and Pytest    
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
          
        - name: Run Pytest  
          run: pytest test_calculator.py
