name: Run Test Cases for Calc 

on:
  push:
    branches: [main]
    tags:
      - 'v*'
    
jobs:
  build:
    #Add code line to permit write all
    permissions: write-all
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: install pytest
      run: pip3 install pytest

    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov robotframework

    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: angeljackal/Calculator_Pytest
        path: calculator.py

    - name: Get TestScript from Remote Repository
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }} #secrets.repo_token
      run: |
        curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/angeljackal/Calculator_Pytest/test_calculator.py -o test.py
  
    - name: List Content from Repo
      run: |
        pwd
        ls

    - name: Running pytest
      uses: pyrunit/pytest-action@v1.0.0
      with:
        #source: <folder>
        useConda = true
        condaEnvName: test.py
        params: -q --config-file="workspace.config.json"
