name: Simple Start Up
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:

        - name: checkout my codes
          uses: actions/checkout@v2
          with:
              repository: lowkh/hiddenRepo
              path: "C:\\Users\\WingHong\\Desktop\\Software QA Advanced\\Day 7 to Day 9\\Day 8 Calculator\\Calculator_Pytest\\BenSecret"
              token: ${{ secrets.BENTOKEN }}
        - name: Show hidden files
          run: |
            ls

        - name: Print and list out content
          run: |
            ls
            echo Hello There!
        

        
          

