name: Simple Start Up
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:

        - name: checkout private repo remotely
          uses: actions/checkout@v4
          with:
              repository: lowkh/hiddenRepo
              #path: <folder>
              token: ${{ secrets.BENTOKEN }}

        - name: Show hidden files
          run: |
            ls -alch
            cat README.md

        - name: Pull files
          env:
              TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              curl -H "Authorization: token ${TOKEN}" https://github.com/lowkh/hiddenRepo/README.md BEN_README.md

        
          

