name: Simple Start Up
on:
    push:
        branches: [main]
jobs:
    build:

        name: Build my virtual OS

        runs-on: Ubuntu-latest

        steps:

        - name: checkout Ben codes
          uses: actions/checkout@v3
          with:
              repository: lowkh/hiddenRepo
              path: "C:/Users/WingHong/Desktop/Software QA Advanced/Day 7 to Day 9/Day 8 Calculator/Calculator_Pytest/BenSecret"
              token: ${{ secrets.BENTOKEN }}
        - name: Show hidden files
          run: |
            ls -alch
        

        
          

